2025-05-28 09:12:17,821 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99262D0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 09:12:18,712 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924E60>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:37,944 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FEB9927EC0>: Failed to establish a new connection: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다'))
2025-05-28 20:51:37,958 - get_df error for BTCUSDT: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-05-28 20:51:37,960 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FEB9924080>: Failed to establish a new connection: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다'))
2025-05-28 20:51:37,962 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FEB9925A90>: Failed to establish a new connection: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다'))
2025-05-28 20:51:39,467 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925940>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:39,467 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99264B0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:39,468 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBD70>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:39,469 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99273E0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:49,474 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927A40>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:49,478 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924500>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:50,475 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99251C0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:50,477 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99272F0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:51,475 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925E20>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:51,477 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBD40>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:52,477 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB96EA120>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:52,479 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992E810>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:53,478 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992F860>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:51:53,480 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992FC20>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:04,479 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99250A0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:04,481 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924C50>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:05,481 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99272F0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:05,482 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99251C0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:06,481 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927620>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:06,483 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926BA0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:07,483 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBE00>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:07,485 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBC50>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:08,484 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992EF00>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:08,486 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992D1F0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:19,486 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EB860>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:19,489 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBBF0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:20,489 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927CB0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:20,491 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926B40>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:21,489 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99253D0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:21,490 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927D40>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:22,490 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924260>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:22,492 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926C60>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:23,491 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992C080>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:23,492 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992F6E0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:34,494 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992EF60>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:34,496 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925B80>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:35,495 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924CB0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:35,496 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925700>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:36,495 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925A90>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:36,497 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926090>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:37,497 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925A00>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:37,498 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB96E9CD0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:38,498 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBE30>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:38,501 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992F710>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:49,500 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992EB70>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:49,502 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992D2B0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:50,500 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBD70>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:50,501 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB97344A0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:51,501 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927A40>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:51,503 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99258B0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:52,503 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927F80>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:52,504 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927EC0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:53,504 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926660>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:52:53,506 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926B10>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:04,506 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992EC00>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:04,508 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB992D0A0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:05,509 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB982A570>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:05,511 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBBC0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:06,510 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926CF0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:06,512 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924E60>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:07,511 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924110>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:07,513 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925D30>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:08,511 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926B40>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:08,513 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925730>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:19,513 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926C90>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:19,516 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927830>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:20,515 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926300>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:20,623 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBCE0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:21,516 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB7212270>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:21,517 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB924B380>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:22,517 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925790>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:22,521 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99252E0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:23,516 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924A70>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:23,520 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924290>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:34,518 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9248BC0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:34,521 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9736810>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:35,520 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBDA0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:35,522 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9924140>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:36,521 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99256D0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:36,523 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925430>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:37,522 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99243E0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:37,524 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927530>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:38,523 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927EC0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:38,526 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926F00>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:49,525 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB98EBC20>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:49,527 - get_df error for BTCUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BTCUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB5E35DC0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:50,526 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB924B3B0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:50,530 - get_df error for ETHUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ETHUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9925F70>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:51,528 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9927AA0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:51,531 - get_df error for BNBUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=BNBUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99277A0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:52,812 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99276B0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:52,815 - get_df error for SOLUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=SOLUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB99268D0>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:53,531 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=30m&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926F90>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 20:53:53,533 - get_df error for ADAUSDT: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=1h&limit=100&symbol=ADAUSDT (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FEB9926360>: Failed to resolve 'fapi.binance.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-28 21:59:10,020 - get_balance error: APIError(code=-2015): Invalid API-key, IP, or permissions for action, request ip: 106.101.128.190
2025-05-28 21:59:10,967 - get_balance error: APIError(code=-2015): Invalid API-key, IP, or permissions for action, request ip: 106.101.128.190
2025-05-28 21:59:11,961 - get_balance error: APIError(code=-2015): Invalid API-key, IP, or permissions for action, request ip: 106.101.128.190
2025-05-28 21:59:12,956 - get_balance error: APIError(code=-2015): Invalid API-key, IP, or permissions for action, request ip: 106.101.128.190
2025-05-28 22:02:46,119 - Telegram error: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=10)
2025-05-28 22:02:51,170 - SOLUSDT LONG@174.04 TP:176.30 SL:172.30 (low)
2025-05-28 22:16:49,373 - BTCUSDT 거래 무시됨: 수량 0
2025-05-28 22:16:51,888 - ETHUSDT SHORT@2665.43 TP:2630.78 SL:2692.09 (low)
2025-05-28 22:16:52,901 - BNBUSDT SHORT@686.58 TP:677.65 SL:693.44 (low)
